# Generated by Django 6.0 on 2025-12-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        # FIRST: Add the new fields
        migrations.AddField(
            model_name='level',
            name='year',
            field=models.PositiveIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        
        # SECOND: Modify existing fields
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        
        # THIRD: Remove old fields
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='level',
            name='order',
        ),
        
        # FOURTH: Set options and constraints (AFTER fields exist)
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['year', 'semester']},
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('year', 'semester')},
        ),
    ]