# Generated by Django 6.0 on 2025-12-08 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_course_options_remove_course_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['course', 'academic_level__year', 'academic_level__semester', 'code']},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='semester',
        ),
        migrations.AddField(
            model_name='unit',
            name='academic_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='attendance.level'),
        ),
    ]
