# Generated by Django 6.0 on 2025-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0004_alter_unit_options_remove_unit_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='unit',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='assigned_units', to='accounts.lecturerprofile'),
        ),
    ]
