# Generated by Django 6.0 on 2025-12-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_unit_lecturer_unit_lecturers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='delivery_mode',
            field=models.CharField(choices=[('physical', 'Physical/In-person'), ('virtual', 'Virtual/Online'), ('hybrid', 'Hybrid')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_type',
            field=models.CharField(choices=[('normal', 'Normal Class'), ('makeup', 'Make-up Class'), ('extra', 'Extra Class'), ('exam', 'Exam Session')], default='normal', max_length=20),
        ),
    ]
